"""
retry_upload_today.py
─────────────────────
One-shot retry of the YouTube upload step for the 2026-05-21 06:00 run that
crashed when the cached YouTube token expired.

The full pipeline (scanner → scriptgen → voiceover → frames → compose →
thumbnail) completed successfully. Only step 7/7 (upload) failed because
the OAuth refresh token had expired and the unattended task couldn't click
through the browser consent screen.

This script mirrors exactly what main.py does at the upload step (lines
~221-228), reusing the already-rendered .mp4, .png thumbnail, and script
JSON from this morning's 06:07:19 run.

When you run this interactively, the browser OAuth window will open ONCE,
you click "Allow" on your Google account, a fresh token is cached at
~/.youtube_token.json, and the video uploads. From then on the daily
scheduled task should resume working — until Google's 7-day testing-mode
expiry kicks in again. Permanent fix: push the OAuth client from Testing
to Production in Google Cloud Console.

Run from inside the video_pipeline directory:

    cd "C:\\Users\\bruno\\OneDrive\\Ambiente de Trabalho\\Workspace\\crypto scanner\\crypto-scanner\\YOUTUBE - faceless channel\\video_pipeline"
    & "C:\\Program Files\\Python312\\python.exe" .\\retry_upload_today.py
"""

import json
import sys
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Paths — derived from the 06:07:19 run timestamp
# ─────────────────────────────────────────────────────────────────────────────
STAMP        = "20260521_060719"

_SCRIPT_DIR  = Path(__file__).resolve().parent              # .../video_pipeline
_CHANNEL_DIR = _SCRIPT_DIR.parent                           # .../YOUTUBE - faceless channel

VIDEO_PATH   = _CHANNEL_DIR / "Videos"        / f"crypto_recap_{STAMP}.mp4"
THUMB_PATH   = _CHANNEL_DIR / "Videos"        / f"thumb_{STAMP}.png"
SCRIPT_PATH  = _CHANNEL_DIR / "Video Scripts" / f"script_{STAMP}.json"


# ─────────────────────────────────────────────────────────────────────────────
# Sanity check — bail before doing anything if a file is missing
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 68)
print("  RETRY UPLOAD — 2026-05-21 06:07:19 run")
print("=" * 68)
print()

missing = [p for p in (VIDEO_PATH, THUMB_PATH, SCRIPT_PATH) if not p.exists()]
if missing:
    print("ERROR — one or more rendered files are missing:")
    for p in missing:
        print(f"  ✗ {p}")
    print()
    print("Cannot retry. Files would need to be regenerated by running the full pipeline.")
    sys.exit(1)

print("Inputs located:")
print(f"  ✓ Video      {VIDEO_PATH.name}  ({VIDEO_PATH.stat().st_size / 1_048_576:.1f} MB)")
print(f"  ✓ Thumbnail  {THUMB_PATH.name}")
print(f"  ✓ Script     {SCRIPT_PATH.name}")
print()


# ─────────────────────────────────────────────────────────────────────────────
# Load script JSON
# ─────────────────────────────────────────────────────────────────────────────
script = json.loads(SCRIPT_PATH.read_text(encoding="utf-8"))
print(f"Loaded script:  title = {script.get('title', '?')!r}")
print(f"                segments = {len(script.get('segments', []))}")
print()


# ─────────────────────────────────────────────────────────────────────────────
# Build a minimal _summary — main.py normally attaches this for the owner
# comment. We don't have the original `summary` dict from this morning's
# scanner ingest, so we attach an empty dict. The owner-comment builder
# will either skip cleanly or use safe defaults.
#
# If the comment step blows up, the upload itself has already succeeded by
# then (upload_to_youtube uploads first, then posts the comment), so the
# video still ships.
# ─────────────────────────────────────────────────────────────────────────────
script["_summary"] = {}


# ─────────────────────────────────────────────────────────────────────────────
# Get fresh credentials — this is the step that pops the OAuth browser
# window. Click "Allow" on your Google account when it appears.
# ─────────────────────────────────────────────────────────────────────────────
print("[1/2] Getting YouTube credentials...")
print("      → If your token expired, a browser window will open NOW.")
print("        Sign in with your channel's Google account and click Allow.")
print()

from upload import get_youtube_credentials, upload_to_youtube  # noqa: E402

creds = get_youtube_credentials()
print("      ✓ Credentials acquired.")
print()


# ─────────────────────────────────────────────────────────────────────────────
# Upload
# ─────────────────────────────────────────────────────────────────────────────
print("[2/2] Uploading to YouTube...")
print("      (this will take 1-3 minutes depending on connection)")
print()

result = upload_to_youtube(
    video_path     = VIDEO_PATH,
    script         = script,
    credentials    = creds,
    thumbnail_path = THUMB_PATH,
)

video_id  = result.get("id", "?")
video_url = f"https://youtu.be/{video_id}"

print()
print("=" * 68)
print(f"  ✓ UPLOADED:  {video_url}")
print("=" * 68)
print()
print("Verify on YouTube Studio. The cached token at ~/.youtube_token.json")
print("should now be fresh, so tomorrow's 06:00 task will work again.")
print()
print("Permanent fix: in Google Cloud Console → APIs & Services →")
print("OAuth consent screen, push the app from 'Testing' to 'In production'.")
print("Tokens in Testing mode expire every 7 days; published apps don't.")
